# Google Cloud Build configuration for CI/CD
steps:
  # Step 1: Run tests
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        pip install -r requirements.txt
        pytest tests/ -v || exit 1
    id: 'run-tests'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/naad-bailgada-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/naad-bailgada-api:latest'
      - './backend'
    id: 'build-image'
    waitFor: ['run-tests']

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/naad-bailgada-api:$COMMIT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/naad-bailgada-api:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'naad-bailgada-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/naad-bailgada-api:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '100'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-south1:naad-bailgada-db'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha', 'push-image-latest']

  # Step 5: Run smoke tests (optional)
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-f'
      - 'https://naad-bailgada-api-XXXXXX-as.a.run.app/health'
    id: 'smoke-test'
    waitFor: ['deploy-cloud-run']

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/naad-bailgada-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/naad-bailgada-api:latest'

# Build timeout
timeout: '1200s'

# Use faster machine type
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
