"""create_marketplace_table

Revision ID: 7a6581a8690c
Revises: add_track_unit_003
Create Date: 2025-12-16 14:02:40.551261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6581a8690c'
down_revision = 'add_track_unit_003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_mobile', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_listings_created_at'), 'marketplace_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_name'), 'marketplace_listings', ['name'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_status'), 'marketplace_listings', ['status'], unique=False)
    op.drop_constraint('admin_users_email_key', 'admin_users', type_='unique')
    op.drop_constraint('admin_users_username_key', 'admin_users', type_='unique')
    op.drop_index('ix_admin_users_email', table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_index('ix_admin_users_username', table_name='admin_users')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.drop_constraint('bulls_registration_number_key', 'bulls', type_='unique')
    op.drop_index('ix_bulls_registration_number', table_name='bulls')
    op.create_index(op.f('ix_bulls_registration_number'), 'bulls', ['registration_number'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_bulls_registration_number'), table_name='bulls')
    op.create_index('ix_bulls_registration_number', 'bulls', ['registration_number'], unique=False)
    op.create_unique_constraint('bulls_registration_number_key', 'bulls', ['registration_number'])
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.create_index('ix_admin_users_username', 'admin_users', ['username'], unique=False)
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index('ix_admin_users_email', 'admin_users', ['email'], unique=False)
    op.create_unique_constraint('admin_users_username_key', 'admin_users', ['username'])
    op.create_unique_constraint('admin_users_email_key', 'admin_users', ['email'])
    op.drop_index(op.f('ix_marketplace_listings_status'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_name'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_created_at'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    # ### end Alembic commands ###
